### ISSUE TITLE
[Bug] 同一文档两张一样的图片，删除其中一个，会把两个图片链接都删除掉

### ISSUE THREAD

**Issue by Yaozhuwa** [martinniee/Obsidian-fast-image-cleaner#1]

**Comment by martinniee** [comment]
严格来说，这不算是Bug,因为这是我意料之内的事情。因为我原本没有打算处理同文档多个同图片，因为预想没有人会这么干😂（就连多个文档引用同个图片一开始没想着处理）。不知道你是出于什么情况发现的😃。实际上在视频中演示的效果也是这样。要是有人有这个需求，后面有时间就修正一下吧。
