### ISSUE TITLE
attachments get deleted before I click delete button when I right click a markdown file and select 'delete file and all its attatchments'

### ISSUE THREAD

**Issue by ghost** [martinniee/Obsidian-fast-image-cleaner#10]
在md文件上右键选择删除文件及其所有附件，弹出确认对话框，尚未点击删除按钮，但此时附件已经被删除。
此外，我的附件文件夹是assets，笔记的附件在assets文件夹下的与笔记同名的文件夹中，删除附件时，附件所在的文件夹丢失，只有附件被移动到了目的位置。

**Comment by ghost** [comment]
感谢及时的修复。
第二个问题，现在删除附件后，同名文件夹也会出现在目的位置，不过同名文件夹和附件的层级关系丢了，比如，删除名为“测试”的笔记后，目的位置出现了“测试”空文件夹、测试.md以及附件。

**Comment by martinniee** [comment]
在 `windows` 中，删除包含多个附件的文件夹，回收站中不会有层级结构，好像`macOS`中可以（顺便问一下你的设备系统？）。不过删除文件的路径上本身带有附件文件夹的路径（父级目录），所以“还原”也会还原附件文件夹（即使还原的时候不选择附件文件夹）。还有你说的“ 目的位置“ 指的的什么？ `.trash` ? ，也试了，似乎也是没有层次结构。不过不建议设置为 `.trash`，因为要还原很麻烦。一般选择删除（文件）了，就删除了，应该没有”还原“的必要，所以我会移动到 系统回收站。

**Comment by ghost** [comment]
> 在 `windows` 中，删除包含多个附件的文件夹，回收站中不会有层级结构，好像`macOS`中可以（顺便问一下你的设备系统？）。不过删除文件的路径上本身带有附件文件夹的路径（父级目录），所以“还原”也会还原附件文件夹（即使还原的时候不选择附件文件夹）。还有你说的“ 目的位置“ 指的的什么？ `.trash` ? ，也试了，似乎也是没有层次结构。不过不建议设置为 `.trash`，因为要还原很麻烦。一般选择删除（文件）了，就删除了，应该没有”还原“的必要，所以我会移动到 系统回收站。

目的位置是插件的设置deleted attachment destination啊。无论设置为系统回收站还是.trash，以下内容都成立：
obsidian中直接在文件夹上右键删除，在目的位置中可以看到这个文件夹以及附件是保持了原来的层级关系的，目的位置中只有文件夹，文件夹下是附件；但是如果用插件删除，文件夹和附件就被“碾平”了，都直接显示在目的位置中。

另外，deleted attachment destination是否可以加一个选项，遵从obsidian本身的设置呢？

**Comment by martinniee** [comment]
> > 在 `windows` 中，删除包含多个附件的文件夹，回收站中不会有层级结构，好像`macOS`中可以（顺便问一下你的设备系统？）。不过删除文件的路径上本身带有附件文件夹的路径（父级目录），所以“还原”也会还原附件文件夹（即使还原的时候不选择附件文件夹）。还有你说的“ 目的位置“ 指的的什么？ `.trash` ? ，也试了，似乎也是没有层次结构。不过不建议设置为 `.trash`，因为要还原很麻烦。一般选择删除（文件）了，就删除了，应该没有”还原“的必要，所以我会移动到 系统回收站。
> 
> 目的位置是插件的设置deleted attachment destination啊。无论设置为系统回收站还是.trash，以下内容都成立： obsidian中直接在文件夹上右键删除，在目的位置中可以看到这个文件夹以及附件是保持了原来的层级关系的，目的位置中只有文件夹，文件夹下是附件；但是如果用插件删除，文件夹和附件就被“碾平”了，都直接显示在目的位置中。

刚刚实验了一下，好像是这样的😂，使用插件的方式，因为文件夹是在附件删除后决定删除的，所以是分别删除的，自然在移动的位置中是是 “碾平”的。因为考虑着都是要被删除了内容了，后面的结果就无所谓了。而且我也不使用 `.trash`文件夹，而 `windows`中 回收站中件夹中的内容不能展开（macOS好像可以）。

**Comment by ghost** [comment]
> 刚刚实验了一下，好像是这样的😂，使用插件的方式，因为文件夹是在附件删除后决定删除的，所以是分别删除的，自然在移动的位置中是是 “碾平”的。因为考虑着都是要被删除了内容了，后面的结果就无所谓了。而且我也不使用 `.trash`文件夹，而 `windows`中 回收站中件夹中的内容不能展开（macOS好像可以）。

我说的层级关系不包括能否展开，只是文件和文件夹的逻辑关系。
至于这个先后删除的问题，我不清楚具体是怎么实现的，是否可以先标记而实际上不删除附件，等判断完文件夹是否需要删除后，再执行删除操作？
还有上边我编辑了一点内容，就是：
deleted attachment destination是否可以加一个选项，遵从obsidian本身的设置呢？

**Comment by martinniee** [comment]
> 另外，deleted attachment destination是否可以加一个选项，遵从obsidian本身的设置呢？

关于 Obsidian 本身的设置，应该指的 这块吧 
![image](https://github.com/martinniee/Obsidian-fast-image-cleaner/assets/55736512/083d4ca8-570e-4657-a6a2-15ff4ab119e1)

你提问题之前的实现就是用的 obsidian 默认文件删除设置（对于删除文件和删除所有附件的功能）。这个实现使用了 obsidain 未暴露的一个 api ，因为没有回调，就只是一个方法，删除会弹出确定窗口，没法控制等待点击确定后执行后面的语句，所以会在未点击确定就把所有附件都删除了。早上修复的时候，自己写了一个 Modal 提示窗口，参照了默认文件删除设置的提示窗口的内容。删除方式也是用的一个 obsidian 中的api，和前面那个未暴露的api不同，此文件删除没有弹窗。如果选择 obsidian 默认的删除的功能（未暴露的api），则会有弹窗，这样会应该会弹出两次（这个设置也可以在 
![image](https://github.com/martinniee/Obsidian-fast-image-cleaner/assets/55736512/baca51af-33ec-4761-9008-d8e3b234bc6a)
 中选择。

**Comment by martinniee** [comment]
> > 刚刚实验了一下，好像是这样的😂，使用插件的方式，因为文件夹是在附件删除后决定删除的，所以是分别删除的，自然在移动的位置中是是 “碾平”的。因为考虑着都是要被删除了内容了，后面的结果就无所谓了。而且我也不使用 `.trash`文件夹，而 `windows`中 回收站中件夹中的内容不能展开（macOS好像可以）。
> 
> 我说的层级关系不包括能否展开，只是文件和文件夹的逻辑关系。 至于这个先后删除的问题，我不清楚具体是怎么实现的，是否可以先标记而实际上不删除附件，等判断完文件夹是否需要删除后，再执行删除操作？ 还有上边我编辑了一点内容，就是： deleted attachment destination是否可以加一个选项，遵从obsidian本身的设置呢？

“ 是否可以先标记而实际上不删除附件，等判断完文件夹是否需要删除后，再执行删除操作？” 
这个可以。
“  deleted attachment destination是否可以加一个选项，遵从obsidian本身的设置呢？ ” 
这个如我上面说的，如果是针对某个文件（或文件夹）可以，连续的操作不好控制先后执行顺序。因为使用系统删除设置，弹窗是是默认封装的，无法控制点击按钮后的回调。

**Comment by ghost** [comment]
> > 另外，deleted attachment destination是否可以加一个选项，遵从obsidian本身的设置呢？
> 
> 关于 Obsidian 本身的设置，应该指的 这块吧 ![image](https://user-images.githubusercontent.com/55736512/251470519-083d4ca8-570e-4657-a6a2-15ff4ab119e1.png)
> 
> 你提问题之前的实现就是用的 obsidian 默认文件删除设置（对于删除文件和删除所有附件的功能）。这个实现使用了 obsidain 未暴露的一个 api ，因为没有回调，就只是一个方法，删除会弹出确定窗口，没法控制等待点击确定后执行后面的语句，所以会在未点击确定就把所有附件都删除了。早上修复的时候，自己写了一个 Modal 提示窗口，参照了默认文件删除设置的提示窗口的内容。删除方式也是用的一个 obsidian 中的api，和前面那个未暴露的api不同，此文件删除没有弹窗。如果选择 obsidian 默认的删除的功能（未暴露的api），则会有弹窗，这样会应该会弹出两次（这个设置也可以在 ![image](https://user-images.githubusercontent.com/55736512/251474501-baca51af-33ec-4761-9008-d8e3b234bc6a.png) 中选择。

我说的遵从obsidian本身设置的意思是，如果obsidian设置的是删除到系统回收站，那么用插件删除时也删除到回收站，如果obsidian设置的是删除到.trash，那用插件就删除到.trash。
如果有这么一个选项，obsidian的删除和插件的删除这两者的目的位置是统一的，如果需要改动，只需要在obsidian设置就可以，而不需要同时在插件中也设置。

**Comment by martinniee** [comment]
“我说的遵从obsidian本身设置的意思是，如果obsidian设置的是删除到系统回收站，那么用插件删除时也删除到回收站，如果obsidian设置的是删除到.trash，那用插件就删除到.trash。” 
你说的这个就是我说的 “默认文件删除设置”。
obsidian插件中 想要探索更多功能，特别是和系统相关的，很多api都是未暴露的，无法得知细节，无能为力。

**Comment by martinniee** [comment]
我后面再到 discord上 询问一下 obsidian 相关开发人员，看是否可以获取默认文件删除设置。我想应该是可以的，这样话，就可以实现你的说的采用obsidian文件删除设置。

**Comment by ghost** [comment]
> 我后面再到 discord上 询问一下 obsidian 相关开发人员，看是否可以获取默认文件删除设置

辛苦！
我是在attachment management这个插件中看到这样一个设置，才有这个想法的。
![图片](https://github.com/martinniee/Obsidian-fast-image-cleaner/assets/127864725/17604013-09f9-4be0-8b92-91a6a765f6da)

**Comment by ghost** [comment]
> 



> 我后面再到 discord上 询问一下 obsidian 相关开发人员，看是否可以获取默认文件删除设置。我想应该是可以的，这样话，就可以实现你的说的采用obsidian文件删除设置。

直接从本地.obsidian中的app.json读取设置，这个是否能做到？

**Comment by martinniee** [comment]
感谢提示，我后面再查看一下这个插件代码的实现，寻找解决办法

**Comment by martinniee** [comment]
> > 
> 
> > 我后面再到 discord上 询问一下 obsidian 相关开发人员，看是否可以获取默认文件删除设置。我想应该是可以的，这样话，就可以实现你的说的采用obsidian文件删除设置。
> 
> 直接从本地.obsidian中的app.json读取设置，这个是否能做到？

应该是有现成的 api的，不过我目前不知道，后面我询问一下。

**Comment by martinniee** [comment]
> > 
> 
> > 我后面再到 discord上 询问一下 obsidian 相关开发人员，看是否可以获取默认文件删除设置。我想应该是可以的，这样话，就可以实现你的说的采用obsidian文件删除设置。
> 
> 直接从本地.obsidian中的app.json读取设置，这个是否能做到？

我已经知道了获取 系统配置信息的方式（果然是一个未暴露的 api ） 😀 。嗯，后续有时间我再修改。
