### ISSUE TITLE
建议：实现针对特定附件文件夹的删除功能

### ISSUE THREAD

**Issue by sjhsbhqf** [martinniee/Obsidian-fast-image-cleaner#11]
缺点：在删除文件夹时，没办法检测文件夹中的图片是否被某些MD文档引用，会直接全部删除掉。

建议：删除附件文件夹时，检测出所有未被引用的图片，并且将它们用链接列表出来形成一个MD文档，然后后续可以在这个MD文档中用您的插件右键删除这些图片附件。或者在删除附件文件夹时，立即提示有些图片未被引用，在确定删除和取消之间提供一个仅删除未被引用图片的按钮。

非常感谢UP主百忙之中写出这个插件，真的很有创意。

**Comment by martinniee** [comment]
> "在删除文件夹时，没办法检测文件夹中的图片是否被某些MD文档引用，会直接全部删除掉。" 

删除文件夹，指的是哪个功能，①右键删除文件同时删除所有引用的附件 还是 ②还是右键图片删除。这两个功能都不是**直接删除附件文件夹**，都是 **当附件所在文件夹仅包含当前要删除的附件且这个附件只被当前笔记引用才删除**。换句话说，某个附件所在的**文件夹**中存在同时被其他笔记（文件）引用的图片（附件）时，就不会删除这个附件所在的（附件）文件夹。你说的情况，这个插件的功能应该是考虑了的，会检测文件夹中的图片是否被某些MD文档引用，不删除也被其他MD文档引用的图片。

如果真的存在这种情况，或许是有其他情况我忽略了？总之，插件设计之初就考虑到了**图片附件被多个笔记引用的情况**，不删除这种情况下的附件，而只删除仅仅被当前笔记引用的附件。

> 删除附件文件夹时，检测出所有未被引用的图片 

未被引用的图片 是什么意思？此插件删除的附件文件是这个附件文件仅被当前笔记引用的情况下，也就是说只有一个笔记（当前操作的笔记）引用它，不存在 未被引用的图片。如果你指的的是附件文件夹中存在 孤立的附件文件（一般情况下，附件文件夹储存的应该是引用的附件，无论是单引用，还是多引用，完全没有被引用的附件不应该放入附件文件夹，除非这个附件是删除了在文档中的引用链接），即使存在这种情况，此插件也不会删除 孤立的 附件。

> 或者在删除附件文件夹时，立即提示有些图片未被引用，在确定删除和取消之间提供一个仅删除未被引用图片的按钮。

对于右键图片删除的功能，因为此功能是针对**单个图片**删除，所以对于 **图片仅被当前笔记引用的情况**，并未给出提示（后续可以考虑加一个，避免用户失误删除），即使不小心删除了，也可在方便地回收站找到。

你说的这个提示，应该指的 另一个功能——删除笔记同时删除所有笔记引用的附件，这里的附件也是指的仅被当前笔记引用的附件。当你使用这个功能——右键笔记选项插件选项，会弹出一个提示窗口，这里面就有提示 当前操作的笔记中仅被当前笔记引用的附件的数量（no-multi-referenced 就是 非 多引用，也就是 **仅被当前笔记引用**）
![image](https://github.com/martinniee/Obsidian-fast-image-cleaner/assets/55736512/56a58ddc-ed39-46ef-a616-a08b85aadf9f)



如果你想要删除 **未被引用的图片** 。社区中有一个插件 `clear-unused-images `满足你的需求。fast image clenaer 插件 和此插件的区别就是 fast image cleaner 删除的是 **被引用**的图片（附件） 而不是 **未被引用**的图片（附件）。


如果可以的话，请你复现你遇到的问题（第一步,第二步....），确保真的存在这种问题（至少我的使用中没有遇到你说的问题）

**Comment by sjhsbhqf** [comment]
@martinniee 非常感谢小姐姐的回复！！！

第一步：创建如下MD文档和图片
![image](https://github.com/martinniee/Obsidian-fast-image-cleaner/assets/41407099/701bcf4c-11d1-4b5e-ac67-9edbb1112ccc)

test2文档中包括test1.assets附件文件夹的图片。


第二步：右键删除test1.assets附件文件夹。弹出下面的提示（并不是提示有哪些图片正被引用），我们点击确定。
![image](https://github.com/martinniee/Obsidian-fast-image-cleaner/assets/41407099/df2f2103-9250-450f-9f75-eb94241285d2)

第三步：我们可以看到test1.assets附件文件夹已经被删除并且里面的图片全没了。
![image](https://github.com/martinniee/Obsidian-fast-image-cleaner/assets/41407099/1277b5c1-a867-4d69-b798-b2241ef62388)
重新打开test2，发现原先引用test1的图片已经失效了。
![image](https://github.com/martinniee/Obsidian-fast-image-cleaner/assets/41407099/5dd41020-2a51-4de3-80d2-5f63236e8978)

所以我的意思是，能不能在删除一个文件夹的时候，提示哪些图片被引用了，谢谢小姐姐！！！

**Comment by martinniee** [comment]
不好意思，我是男的。  😄 
似乎你搞错了 😃 ，你 上面所描述的右键删除功能是 obsidian 系统提供的 删除选项。我的插件的删除选项只会在**右键文件**（而不是文件夹）的时候显示

1： 右键文件夹不会显示删除选项

![image](https://github.com/martinniee/Obsidian-fast-image-cleaner/assets/55736512/0d1950fc-4d6a-44ea-9441-358e25d8070e)


2： 右键文件时会显示删除选项

![image](https://github.com/martinniee/Obsidian-fast-image-cleaner/assets/55736512/ceec3c92-180e-4af8-b552-30c7f1f3fb99)

**Comment by sjhsbhqf** [comment]
原来如此，我已经摸索出了一套很有效的工作流：将插件Fast Image Cleaner和插件Find orphaned files and broken links搭配使用。插件Find orphaned files and broken links使你用`Find orphaned files`将附件文件夹中所有未被引用的图片列出在MD文档，然后使用插件Fast Image Cleaner的右键附件链接删除功能——删除掉除该MD文档引用而其他文档未引用的附件。

谢谢你！！！
