### ISSUE TITLE
右键附件里的图片删除时，会删除文档中所有图片

### ISSUE THREAD

**Issue by sjhsbhqf** [martinniee/Obsidian-fast-image-cleaner#12]
右键附件里的图片删除时，会删除文档中所有图片。如下所示

![image](https://github.com/martinniee/Obsidian-fast-image-cleaner/assets/41407099/afea5b33-44ed-490a-ab73-4cd26dc92020)

![image](https://github.com/martinniee/Obsidian-fast-image-cleaner/assets/41407099/db1215ea-74a5-4035-8fe1-f6c8c82f1d02)

**Comment by martinniee** [comment]
你说的和 #13 是一样的吗，其他的引用链接也都被删除了？ 最近频繁出现这个问题，我想肯定因为某种共同的原因。我当前使用没出现这种问题，并且之前也没出现过。是否你们更新了 obsidian 版本导致的？建议尝试单独创建一个库测试该情况会重复出现，还有就是提供一下软件设备版本之类的。

**Comment by sjhsbhqf** [comment]
刚刚做了新的尝试，当我新建库的时候，就没有这个问题了。

然而我实在找不到相关原因，我的obsidian版本是1.4.5。

我可以把我的配置文件、插件文件等发给您，您看方便以蓝奏云的方式接收吗？

https://wwwl.lanzouw.com/b023bc1za
密码:hc7s

**Comment by martinniee** [comment]
> 刚刚做了新的尝试，当我新建库的时候，就没有这个问题了。
> 
> 然而我实在找不到相关原因，我的obsidian版本是1.4.5。
> 
> 我可以把我的配置文件、插件文件等发给您，您看方便以蓝奏云的方式接收吗？
> 
> https://wwwl.lanzouw.com/b023bc1za 密码:hc7s

好的，我有空试试
