### ISSUE TITLE
All images attached to a note are deleted

### ISSUE THREAD

**Issue by alberti42** [martinniee/Obsidian-fast-image-cleaner#13]
When I right click on an image and select from the contextual menu to delete the attachment, as a result, all images attached to that note are deleted from note. It happens that only the image I selected is moved to the trash bin, while the others remain in teh folder. However, the internal references to those other images are removed from the markdown. So, all images disappeared from the note, effectively, it looks as if they were all deleted.

Is this behavior intended? Probably not. I wished only the image I right click on was deleted, without affecting all other images.

**Comment by martinniee** [comment]
Absolutely not; this has never happened before. Recently, another user #12 also reported this problem; consequently, I think it is no accident. However, I am currently using this plugin and am not experiencing any problems. Please create another new vault to verify whether that is a persistent issue for you (another user reported that it was fine while creating a new vault with the plugin, and everything worked).

**Comment by alberti42** [comment]
Thanks for the quick reply, Nathaniel! I will do in the next days some debugging. Most likely it is caused by a bad interaction with another plugin. I will have to find out which and then report more about.

**Comment by alberti42** [comment]
I found the time to debug the problem. I disabled all other plugin and experimented. I found out that the problem is not caused by an interference with any other plugin. It is however related to how the plugin [Attachment manager](https://github.com/chenfeicqq/obsidian-attachment-manager) works.

All my attachments were added to subfolders carrying the name of the note + "_attachments". For example, if I had a note called `mynote.md`, the plugin `Attachment manager` creates a subfolder called `mynote.md_attachments`, where the attachments are then stored.

What caused the problem of all images being deleted from, say, `mynote.md` when I intended to delete only one image is the name of the attachment folder containing `.md`.

I really like your plugin, `Fast image cleaner`, and wanted to keep using it. As a work-around, I decided to use the [ Attachment Management](https://github.com/trganda/obsidian-attachment-management) plugin. This offers something less than the newer plugin mentioned above, but on the upside, it does not add `.md` to the name of the subfolders containing my attachments.

So, everything works at this point with me. However, it would be great if you could reproduce the bug using subfolders for the attachments with a dot in their name, and find a fix to this very tiny bug.

Thank you a lot for your development!

**Comment by martinniee** [comment]
Thank you for your valuable feedback. I believe I've identified the issue, which stems from the original code I wrote for the plugin (it's been a while, and I wasn't previously aware of it). However, thanks to your reports, I promptly initiated debugging and successfully pinpointed the problem.

I will resolve this issue when I have some spare time.

**Comment by lxq1** [comment]
Hello developer, this plug-in is very useful for obsidian's image management. I also encountered the same BUG problem. When will this BUG be fixed? Thank you very much for your efforts

**Comment by lxq1** [comment]
附件的路径包含符号 `.`  点的原因

**Comment by martinniee** [comment]
> Hello developer, this plug-in is very useful for obsidian's image management. I also encountered the same BUG problem. When will this BUG be fixed? Thank you very much for your efforts

感谢提醒，好长时间都忘了这个问题，本地已经修复了，应该没问题了，后面在上传。

**Comment by jerrygreen** [comment]
This still seems to be the issue. I'm not sure exactly how to reproduce since it worked fine when «Move to Obsidian trash» option was used. This might not be related but when I changed it to «Move to System Trash», it now deletes a whole bunch of files in the document I'm working, instead of deleting just this one image I selected.

Obsidian v1.5.3
Plugin v0.8.2
