### ISSUE TITLE
鼠标右键后，不再弹出删除按钮。在沙箱中测试也是如此

### ISSUE THREAD

**Issue by ku-zhen** [martinniee/Obsidian-fast-image-cleaner#16]
obsidian版本1.5.10，插件版本最新。

**Comment by LouisGameDev** [comment]
问题是这一行代码。The regex does not seem to be matching paths correctly and I can't understand what it's doing. https://github.com/martinniee/Obsidian-fast-image-cleaner/blame/f519b8a079fc951908bac9a4a616cd0c1d186513/src/main.ts#L125

我修复了我自己的本地版本，这是我的可以使用的版本：
I fixed the problem locally, here's my working function. 

```javascript
  onClick(event) {
    var _a;
    const target = getMouseEventTarget(event);
    const nodeType = target.localName;
    const currentMd = app.workspace.getActiveFile();
    const menu = new import_obsidian7.Menu();
    // const fileBasenameRegex = new RegExp(new RegExp("(?<=\\/)[^\\/]*\\.[\\w\\d]+$"));
    let imgPath = "";
    const delTargetType = ["img", "iframe", "video", "div", "audio"];
    if (delTargetType.includes(nodeType)) {
      imgPath = (_a = target.parentElement) == null ? void 0 : _a.getAttribute("src");
      console.log(imgPath);
      // const fileBaseName = imgPath.match(fileBasenameRegex)[0];
      this.addMenu(menu, imgPath, currentMd);
    }
    this.registerEscapeButton(menu);
    menu.showAtPosition({ x: event.pageX, y: event.pageY - 40 });
    this.app.workspace.trigger("NL-fast-file-cleaner:contextmenu", menu);
  }
};
```

Because I haven't tested this extensively or understand the original authors intent, I won't create a pull-request for this change.

**Comment by ku-zhen** [comment]
> 问题是这一行代码。The regex does not seem to be matching paths correctly and I can't understand what it's doing. https://github.com/martinniee/Obsidian-fast-image-cleaner/blame/f519b8a079fc951908bac9a4a616cd0c1d186513/src/main.ts#L125问题是这一行代码。正则表达式似乎没有正确匹配路径，我无法理解它在做什么。https://github.com/martinniee/Obsidian-fast-image-cleaner/blame/f519b8a079fc951908bac9a4a616cd0c1d186513/src/main.ts#L125
> 
> 我修复了我自己的本地版本，这是我的可以使用的版本： I fixed the problem locally, here's my working function.
> 
> ```js
>   onClick(event) {
>     var _a;
>     const target = getMouseEventTarget(event);
>     const nodeType = target.localName;
>     const currentMd = app.workspace.getActiveFile();
>     const menu = new import_obsidian7.Menu();
>     // const fileBasenameRegex = new RegExp(new RegExp("(?<=\\/)[^\\/]*\\.[\\w\\d]+$"));
>     let imgPath = "";
>     const delTargetType = ["img", "iframe", "video", "div", "audio"];
>     if (delTargetType.includes(nodeType)) {
>       imgPath = (_a = target.parentElement) == null ? void 0 : _a.getAttribute("src");
>       console.log(imgPath);
>       // const fileBaseName = imgPath.match(fileBasenameRegex)[0];
>       this.addMenu(menu, imgPath, currentMd);
>     }
>     this.registerEscapeButton(menu);
>     menu.showAtPosition({ x: event.pageX, y: event.pageY - 40 });
>     this.app.workspace.trigger("NL-fast-file-cleaner:contextmenu", menu);
>   }
> };
> ```
> 
> Because I haven't tested this extensively or understand the original authors intent, I won't create a pull-request for this change.

修改后正常工作了，感谢！It works, thanks.

**Comment by martinniee** [comment]
此问题之前本地发现且修改了，但没有上传，现已更新版本！
