### ISSUE TITLE
[建議與感謝] 希望能有圖片重新命名的功能

### ISSUE THREAD

**Issue by kin30528** [martinniee/Obsidian-fast-image-cleaner#17]
謝謝 @martinniee 對這款插件的開發和維護，之前觀望一陣子因為插件不能成功刪除圖片，
但近期的更新終於能成功刪除圖片了，解決了我長期的困擾😊

關於圖片，雖然 [Paste image rename](https://github.com/reorx/obsidian-paste-image-rename) 能在貼入圖片之前重新命名，
但後期管理圖片時，希望能**透過修改連結同時修改到圖片名稱**，
畢竟圖片不會被視為一份筆記，要點進連結後再命名較不直覺，也較麻煩
不曉得插件是否能做到這樣的功能？
再次感謝你開發這個插件~

**Comment by martinniee** [comment]
感谢你的提议。你说的功能好像被一个fork了我的插件实现，并且提供了更多附件（图片）功能支持，请你试用这个插件看看。那个插件叫做 attachflow https://github.com/Yaozhuwa/AttachFlow ，此插件目前在插件市场找不到，可以手动安装或者用 brat 插件安装。因本人是业余的，由于个人时间和能力限制，没法继续开发，恰好有人接续的我的项目，对于无法完成实现你的需求对此感到抱歉。
