### ISSUE TITLE
当图片标明尺寸等信息时，并不会将引用链接从笔记中清除

### ISSUE THREAD

**Issue by ku-zhen** [martinniee/Obsidian-fast-image-cleaner#2]
你好，当图片引用格式类似 `![[xxxx.png|450]]` 格式时，执行清除图片命令，会删除附件，但并不会删除文件中的链接。

**Comment by martinniee** [comment]
对于这个问题，我之前处理链接的时候没考虑到这种情况（因为我不用 `| xxx ` 语法 设置图片尺寸），后续有时间考虑修复一下 😄

**Comment by martinniee** [comment]
fixed
