### ISSUE TITLE
deprecated...

### ISSUE THREAD

**Issue by zhouxinghong** [martinniee/Obsidian-fast-image-cleaner#3]
deprecated...

**Comment by martinniee** [comment]
The reason I only support it in Live View and Reading View is for the way to trigger image deletion. I have no idea about How to clear the image in source mode. Is it just to right-click on the reference link of the image and then provide an option on the context menu or else? Maybe the image in source mode cannot be previewed, and the most important point is that the Live view and Reading view are frequently for people to use, at least for me.
If you have any ideas, please tell me.

**Comment by zhouxinghong** [comment]
Completely correct! 👍😜
Reference links to images can be right-clicked and provide a delete option on the context menu. Since I never use preview mode, I believe there are many users like me who prefer to edit notes in source mode. . .

**Comment by martinniee** [comment]
OK.I will try

**Comment by zhouxinghong** [comment]
Improvement is needed: the reading mode should not provide a delete function, if so, in many cases, it will cause user misoperation and cause user data loss.
The delete function is limited to edit mode including: LIVE mode and source code mode. . .
