### ISSUE TITLE
Doesn't load `undefined (reading 'deleteOption')`

### ISSUE THREAD

**Issue by huyz** [martinniee/Obsidian-fast-image-cleaner#4]
For me, the plugin doesn't load

![screenshot 2023-04-12T120258Z](https://user-images.githubusercontent.com/128394/231451376-3858a2da-c137-4482-812f-e4f87b5d0e05.png)

I tried changing the delete option but made no difference.

Fast Image Cleaner Version: 0.5.1
Obsidian Version 1.2.2 (Installer 1.1.16)

**Comment by martinniee** [comment]
Perhaps some plugins are causing this result, try to check for the impact by disabling certain plugins

> For me, the plugin doesn't load
> 
> ![screenshot 2023-04-12T120258Z](https://user-images.githubusercontent.com/128394/231451376-3858a2da-c137-4482-812f-e4f87b5d0e05.png)
> 
> I tried changing the delete option but made no difference.
> 

> Fast Image Cleaner Version: 0.5.1 Obsidian Version 1.2.2 (Installer 1.1.16)

For 
> I tried changing the delete option but made no difference.

In the previous version, I encountered the bug as well. Finally, I found that the Custom Attachment Location plugin may have an impact, but it has no effect after updating the version.

I just found this plugin may be the reason causing the bug in the screenshot as below.
![image](https://user-images.githubusercontent.com/55736512/231462898-fdbe9b2c-d09d-477d-a10a-bab8a8e09720.png)

**Comment by huyz** [comment]
I disabled Settings Search and the JS Console error went away.

But the Trash Can icon still doesn't show up when I hover an image.

I don't see any more JS console errors, unfortunately

**Comment by martinniee** [comment]
?.Where the trash icon is. Oh, Maybe what you said is in the video in readme.md. I have to say sorry that I haven't updated the content yet. The content that the video has demonstrated is an old version. The latest version does not support deleting a file by clicking the trash icon when hovering over an image. Now only deleting the image by right click image with the context menu item is supported

**Comment by huyz** [comment]
Oh yeah, i was looking for the trash icon from the video.

But still, I can't seem to find anything different in the context menu:

![screenshot 2023-04-13T141258Z](https://user-images.githubusercontent.com/128394/231786580-974a74f9-857d-4582-a483-2e4d02a13ddf.png)

**Comment by martinniee** [comment]
That is strange, Can u create another new vault to test if it works ?
