### ISSUE TITLE
Request for feature

### ISSUE THREAD

**Issue by johnsonblue75** [martinniee/Obsidian-fast-image-cleaner#6]
Hi! I like your plugin. I use a custom attachment thing, though I'm not sure if that matters. Your plugin works well, but could you add a feature where: you can simply delete all the images referenced on a page regardless of circumstances? There are a variety of external apps I use (but they do not integrate with Obsidian) - so I'll just copy and paste - and a whole bunch of unhelpful things come in (e.g. social media icons, gmail signatures, profile pictures, etc. It would be nice to retain the text formatting but be able to nuke all the images Thanks for your consideration.

**Comment by martinniee** [comment]
So do you intend to delele all embed files in the note but deleting the note itself ?  Similar to that, the plugin have a feature now that you can delete  not only  all embed files in the note but also note at the same time. This is not a problem if you are going to do it, I will provide a command for that. 😄

**Comment by martinniee** [comment]
> Hi! I like your plugin. I use a custom attachment thing, though I'm not sure if that matters. Your plugin works well, but could you add a feature where: you can simply delete all the images referenced on a page regardless of circumstances? There are a variety of external apps I use (but they do not integrate with Obsidian) - so I'll just copy and paste - and a whole bunch of unhelpful things come in (e.g. social media icons, gmail signatures, profile pictures, etc. It would be nice to retain the text formatting but be able to nuke all the images Thanks for your consideration.

I have added the feature you mentioned, and if you like my plugin , please give it a star 😄
