### ISSUE TITLE
希望再加入一个，在资源管理器中显示源文件

### ISSUE THREAD

**Issue by Jugui-Lin** [martinniee/Obsidian-fast-image-cleaner#7]
这个插件很好用，就是有时候我右键想在资源管理器中显示该图片或者附件，就会激活这个插件，然后我必须关闭这个插件才能在资源管理器中显示，所以希望再加入一个在资源管理器中显示附件这个功能按钮

**Comment by martinniee** [comment]
> 这个插件很好用，就是有时候我右键想在资源管理器中显示该图片或者附件，就会激活这个插件，然后我必须关闭这个插件才能在资源管理器中显示，所以希望再加入一个在资源管理器中显示附件这个功能按钮

这个插件 https://github.com/NomarCub/obsidian-copy-url-in-preview 新增了你说的功能，建议下载（更新）这个插件
![image](https://github.com/martinniee/Obsidian-fast-image-cleaner/assets/55736512/29dfed6d-b705-44fe-af2b-d81e2d1a604a)
